"""empty message

Revision ID: 5235cf2e0a7e
Revises: e51aa4e4284c
Create Date: 2020-04-08 21:01:57.996176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5235cf2e0a7e'
down_revision = 'e51aa4e4284c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('function',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roomname', sa.String(length=100), nullable=True),
    sa.Column('roomadmin', sa.String(length=100), nullable=True),
    sa.Column('roomleader', sa.String(length=100), nullable=True),
    sa.Column('intemperature', sa.String(length=100), nullable=True),
    sa.Column('inhumidity', sa.String(length=100), nullable=True),
    sa.Column('outtemperature', sa.String(length=100), nullable=True),
    sa.Column('outhumidity', sa.String(length=100), nullable=True),
    sa.Column('waterlave', sa.String(length=100), nullable=True),
    sa.Column('lightlave', sa.String(length=100), nullable=True),
    sa.Column('watermoney', sa.String(length=100), nullable=True),
    sa.Column('lightmoney', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('introduction', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('myclass', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('number', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('phone', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('room', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('roommate1', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('roommate2', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('roommate3', sa.String(length=100), nullable=True))
    op.drop_index('username', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('username', 'user', ['username'], unique=True)
    op.drop_column('user', 'roommate3')
    op.drop_column('user', 'roommate2')
    op.drop_column('user', 'roommate1')
    op.drop_column('user', 'room')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'number')
    op.drop_column('user', 'myclass')
    op.drop_column('user', 'introduction')
    op.drop_column('user', 'email')
    op.drop_column('user', 'department')
    op.drop_table('function')
    # ### end Alembic commands ###
