"""empty message

Revision ID: af5c08649eee
Revises: 
Create Date: 2020-05-17 15:39:02.255382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af5c08649eee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet',
    sa.Column('petid', sa.Integer(), nullable=False),
    sa.Column('petname', sa.String(length=100), nullable=True),
    sa.Column('starvation', sa.String(length=100), nullable=True),
    sa.Column('birth', sa.DateTime(), nullable=True),
    sa.Column('FeedTime', sa.DateTime(), nullable=True),
    sa.Column('Feedinginterval', sa.Integer(), nullable=True),
    sa.Column('petpic', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('petid')
    )
    op.create_table('plant',
    sa.Column('plantid', sa.Integer(), nullable=False),
    sa.Column('plantname', sa.String(length=100), nullable=True),
    sa.Column('water', sa.String(length=100), nullable=True),
    sa.Column('watertime', sa.DateTime(), nullable=True),
    sa.Column('waterinterval', sa.Integer(), nullable=True),
    sa.Column('plantpic', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('plantid')
    )
    op.create_table('room',
    sa.Column('roomid', sa.Integer(), nullable=False),
    sa.Column('roomname', sa.String(length=100), nullable=True),
    sa.Column('roomadmin', sa.String(length=100), nullable=True),
    sa.Column('roomleader', sa.String(length=100), nullable=True),
    sa.Column('currentnumber', sa.Integer(), nullable=True),
    sa.Column('intemperature', sa.String(length=100), nullable=True),
    sa.Column('inhumidity', sa.String(length=100), nullable=True),
    sa.Column('outtemperature', sa.String(length=100), nullable=True),
    sa.Column('outhumidity', sa.String(length=100), nullable=True),
    sa.Column('equipmentstatus', sa.String(length=100), nullable=True),
    sa.Column('suspecteddamage', sa.String(length=100), nullable=True),
    sa.Column('reportinformation', sa.String(length=100), nullable=True),
    sa.Column('cleancondition', sa.String(length=100), nullable=True),
    sa.Column('safety', sa.String(length=100), nullable=True),
    sa.Column('waterlave', sa.Integer(), nullable=True),
    sa.Column('lightlave', sa.Integer(), nullable=True),
    sa.Column('watermoney', sa.Integer(), nullable=True),
    sa.Column('lightmoney', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('roomid')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('number', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('roomid', sa.Integer(), nullable=True),
    sa.Column('roomname', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('myclass', sa.String(length=100), nullable=True),
    sa.Column('roommate1', sa.String(length=100), nullable=True),
    sa.Column('roommate2', sa.String(length=100), nullable=True),
    sa.Column('roommate3', sa.String(length=100), nullable=True),
    sa.Column('roomidentity', sa.String(length=100), nullable=True),
    sa.Column('introduction', sa.String(length=100), nullable=True),
    sa.Column('userpic', sa.String(length=100), nullable=True),
    sa.Column('petid', sa.Integer(), nullable=True),
    sa.Column('plantid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('orderid', sa.Integer(), nullable=False),
    sa.Column('orderdate', sa.DateTime(), nullable=True),
    sa.Column('watercost', sa.Integer(), nullable=True),
    sa.Column('lightcost', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('orderid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('user')
    op.drop_table('room')
    op.drop_table('plant')
    op.drop_table('pet')
    # ### end Alembic commands ###
