"""empty message

Revision ID: ed744d03c495
Revises: 
Create Date: 2020-04-13 10:49:59.277142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed744d03c495'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('roomid', sa.Integer(), nullable=False),
    sa.Column('roomname', sa.String(length=100), nullable=True),
    sa.Column('roomadmin', sa.String(length=100), nullable=True),
    sa.Column('roomleader', sa.String(length=100), nullable=True),
    sa.Column('intemperature', sa.String(length=100), nullable=True),
    sa.Column('inhumidity', sa.String(length=100), nullable=True),
    sa.Column('outtemperature', sa.String(length=100), nullable=True),
    sa.Column('outhumidity', sa.String(length=100), nullable=True),
    sa.Column('waterlave', sa.Integer(), nullable=True),
    sa.Column('lightlave', sa.Integer(), nullable=True),
    sa.Column('watermoney', sa.Integer(), nullable=True),
    sa.Column('lightmoney', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('roomid')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('number', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('roomid', sa.Integer(), nullable=True),
    sa.Column('roomname', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('myclass', sa.String(length=100), nullable=True),
    sa.Column('roommate1', sa.String(length=100), nullable=True),
    sa.Column('roommate2', sa.String(length=100), nullable=True),
    sa.Column('roommate3', sa.String(length=100), nullable=True),
    sa.Column('introduction', sa.String(length=100), nullable=True),
    sa.Column('userpic', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('room')
    # ### end Alembic commands ###
