"""empty message

Revision ID: fab8cfd15cdb
Revises: 
Create Date: 2020-04-11 21:14:59.267605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fab8cfd15cdb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('roomid', sa.Integer(), nullable=False),
    sa.Column('roomname', sa.String(length=100), nullable=True),
    sa.Column('roomadmin', sa.String(length=100), nullable=True),
    sa.Column('roomleader', sa.String(length=100), nullable=True),
    sa.Column('intemperature', sa.String(length=100), nullable=True),
    sa.Column('inhumidity', sa.String(length=100), nullable=True),
    sa.Column('outtemperature', sa.String(length=100), nullable=True),
    sa.Column('outhumidity', sa.String(length=100), nullable=True),
    sa.Column('waterlave', sa.Float(), nullable=True),
    sa.Column('lightlave', sa.Float(), nullable=True),
    sa.Column('watermoney', sa.Float(), nullable=True),
    sa.Column('lightmoney', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('roomid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room')
    # ### end Alembic commands ###
